version: '3.8'

services:
  tunnel:
    image: loopbackkr/tunnel:latest
    tty: true
    stdin_open: true
    container_name: ssh_tunnel
    hostname: Tunnel
    restart: always
    ports:
      - '22222:22'
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - PUB_KEY='<YOUR-PUBLIC-KEY>'
